name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'

      - name: Install dependencies
        run: |
          composer install
          sudo apt-get update
          sudo apt-get install -y libpng-dev libjpeg-dev libfreetype6-dev

      - name: Run WordPress
        run: |
          docker run -d --name wordpress -p 8080:80 wordpress:latest
          
      - name: Wait for WordPress to start
        run: sleep 30

      - name: Copy WordPress files to a directory
        run: |
          docker cp wordpress:/var/www/html ./wordpress

      - name: Set WP_LOAD_PATH environment variable
        run: echo "WP_LOAD_PATH=$(pwd)/wordpress/wp-load.php" >> $GITHUB_ENV

      - name: Run PHPUnit
        run: |
          vendor/bin/phpunit --configuration phpunit.xml
